### ISSUE TITLE
自然辅助码是如何分词的?

### ISSUE THREAD

**Issue by raymond8825** [Kepeirui/ZRM_Aux-code#1]
首先感谢大佬和手心输入法为双拼输入法做出的贡献.我是一个双拼新手.双拼我使用的是小鹤双拼,但是没有学习小鹤双形.因为我觉得小鹤双形拆得太细,同时有各种各样的规则,还需要练习官方指定的500简字,不够统一,我也没有快速打字的需求,反而需要经常打长句.后来了解到自然辅助码,发现自然辅助码在双形上入手比小鹤要简单,所以目前我使用的是**小鹤双拼+自然辅助码**.或许等有机会再去尝试小鹤音形吧.再次感谢大佬做出的贡献.期待您的查询辅码的小程序.同时您能讲解一下自然辅助码是如何拆分字的吗?网络上的[文章](https://zhuanlan.zhihu.com/p/122866844)看完,感觉还是不能理解透彻...

**Comment by Kepeirui** [comment]
我看了一下你所引的文章，发现它讲得其实很详细了，基本也做到全覆盖了，我稍微总结一下其实就是：
1. 非独体字的字，首码取部首（此部首指的是新华字典规范好的部首，而非简单的从左到右从上到下这样，例如“剪”，严格上应为dq而非qd），尾码取整个剩余部分。需要补充的是，若剩余的部分太复杂或并非一个字（即没对应的读音），可取剩余部分中又最尾的部件，如“賯”，可取bz，即“貝”和“子”；
2. 独体字的话，首码取笔顺的首笔，尾码取笔顺的尾笔；
3. 有点需要纠正的瑕疵，好像没有“双形”这样的说法（虽然有点别扭的情况下能懂你的意思；
祝你学习顺利吧，其实自然码双拼也很好的，也许把主码和辅码统一使用会更加舒服顺手！

**Comment by Kepeirui** [comment]
> 首先感谢大佬和手心输入法为双拼输入法做出的贡献.我是一个双拼新手.双拼我使用的是小鹤双拼,但是没有学习小鹤双形.因为我觉得小鹤双形拆得太细,同时有各种各样的规则,还需要练习官方指定的500简字,不够统一,我也没有快速打字的需求,反而需要经常打长句.后来了解到自然辅助码,发现自然辅助码在双形上入手比小鹤要简单,所以目前我使用的是**小鹤双拼+自然辅助码**.或许等有机会再去尝试小鹤音形吧.再次感谢大佬做出的贡献.期待您的查询辅码的小程序.同时您能讲解一下自然辅助码是如何拆分字的吗?网络上的[文章](https://zhuanlan.zhihu.com/p/122866844)看完,感觉还是不能理解透彻...

我看了一下你所引的文章，发现它讲得其实很详细了，基本也做到全覆盖了，我稍微总结一下其实就是：
1. 非独体字的字，首码取部首（此部首指的是新华字典规范好的部首，而非简单的从左到右从上到下这样，例如“剪”，严格上应为dq而非qd），尾码取整个剩余部分。需要补充的是，若剩余的部分太复杂或并非一个字（即没对应的读音），可取剩余部分中又最尾的部件，如“賯”，可取bz，即“貝”和“子”；
2. 独体字的话，首码取笔顺的首笔，尾码取笔顺的尾笔；
有点需要纠正的瑕疵，好像没有“双形”这样的说法（虽然有点别扭的情况下能懂你的意思；
祝你学习顺利吧，其实自然码双拼也很好的，也许把主码和辅码统一使用会更加舒服顺手！

**Comment by raymond8825** [comment]
谢谢回复,结合知乎和您对自然辅助码的总结,我现在已经理解了自然辅助码的使用规则了,我希望把您的总结贴到那篇知乎文章的回复下面,让更多双拼新手看到,并会引用和说明您的仓库地址,您觉得怎么样?

**Comment by Kepeirui** [comment]
> 谢谢回复,结合知乎和您对自然辅助码的总结,我现在已经理解了自然辅助码的使用规则了,我希望把您的总结贴到那篇知乎文章的回复下面,让更多双拼新手看到,并会引用和说明您的仓库地址,您觉得怎么样?

完全可以呀，也谢谢你对自然码推广做的贡献哟！

**Comment by raymond8825** [comment]
好的,大佬客气了,我只是一个搬运工(*^▽^*)
